/*
 * Gasper Master API
 *
 * Handles authentication, creation/management of applications, databases, users and also provides a superuser API. <br><br> Only a superuser can avail the superuser API. A superuser can **grant/revoke** superuser privileges to other users. A default  superuser is created every time a Gasper instance is launched whose credentials are defined in the `admin` section of `config.toml`, the main configuration file. A sample configuration file is available [here](https://github.com/sdslabs/gasper/blob/develop/config.sample.toml#L37).<br><br> **Note:-** Normally the applications and databases can only be managed by their owners but the superuser can bypass that check.<br><br> **PS:-** If you want to programmatically generate a client for this API, you can find the corresponding OpenAPI specifications [here](https://github.com/sdslabs/gasper/tree/develop/docs/content/api/specs). We recommend using [OpenAPI-Generator](https://openapi-generator.tech/) for generating clients.
 *
 * API version: 1.0
 * Contact: contact@sdslabs.co.in
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreatedApplication struct for CreatedApplication
type CreatedApplication struct {
	// ID of the application's docker container
	ContainerId string `json:"container_id,omitempty"`
	// Port assigned by the node to the application's docker container
	ContainerPort int64 `json:"container_port,omitempty"`
	// Docker image used in building the application's container
	DockerImage string `json:"docker_image,omitempty"`
	// The domain name of the application (DNS entry is managed by GenDNS 💡)
	AppUrl string `json:"app_url,omitempty"`
	// IPv4 address of the node
	HostIp string `json:"host_ip,omitempty"`
	// The DNS NameServers used by the application's docker container
	NameServers []string `json:"name_servers,omitempty"`
	// The kind of instance this application belongs to
	InstanceType string `json:"instance_type,omitempty"`
	// The programming language in which the application is written
	Language string `json:"language,omitempty"`
	// Owner of the application
	Owner string `json:"owner,omitempty"`
	// Command to SSH into the application's docker container
	SshCmd string `json:"ssh_cmd,omitempty"`
	// Application's identifier assigned by MongoDB
	Id string `json:"_id,omitempty"`
}
