/*
 * Gasper Master API
 *
 * Handles authentication, creation/management of applications, databases, users and also provides a superuser API. <br><br> Only a superuser can avail the superuser API. A superuser can **grant/revoke** superuser privileges to other users. A default  superuser is created every time a Gasper instance is launched whose credentials are defined in the `admin` section of `config.toml`, the main configuration file. A sample configuration file is available [here](https://github.com/sdslabs/gasper/blob/develop/config.sample.toml#L37).<br><br> **Note:-** Normally the applications and databases can only be managed by their owners but the superuser can bypass that check.<br><br> **PS:-** If you want to programmatically generate a client for this API, you can find the corresponding OpenAPI specifications [here](https://github.com/sdslabs/gasper/tree/develop/docs/content/api/specs). We recommend using [OpenAPI-Generator](https://openapi-generator.tech/) for generating clients.
 *
 * API version: 1.0
 * Contact: contact@sdslabs.co.in
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Metrics struct for Metrics
type Metrics struct {
	// Document's identifier assigned by MongoDB
	Id string `json:"_id,omitempty"`
	// Name of the application
	Name string `json:"name,omitempty"`
	// IPv4 address of the node where the application is deployed
	HostIp string `json:"host_ip,omitempty"`
	// Is the application up and running?
	Alive bool `json:"alive,omitempty"`
	// The number of available CPUs in the node
	OnlineCpus int32 `json:"online_cpus,omitempty"`
	// Fraction of total CPUs utilized by the application
	CpuUsage float64 `json:"cpu_usage,omitempty"`
	// Fraction of memory utilized by the application
	MemoryUsage float64 `json:"memory_usage,omitempty"`
	// Highest fraction of memory utilized by the application in its lifetime
	MaxMemoryUsage float64 `json:"max_memory_usage,omitempty"`
	// Memory (in GigaBytes) alloted to the application
	MemoryLimit float32 `json:"memory_limit,omitempty"`
	// Unix timestamp of the metrics document
	Timestamp int64 `json:"timestamp,omitempty"`
}
