// Code generated by MockGen. DO NOT EDIT.
// Source: api_apps.go

// Package testmocks is a generated GoMock package.
package testmocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	openapi "github.com/sdslabs/gctl/client"
	http "net/http"
	reflect "reflect"
)

// MockAppsAPI is a mock of AppsAPI interface
type MockAppsAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAppsAPIMockRecorder
}

// MockAppsAPIMockRecorder is the mock recorder for MockAppsAPI
type MockAppsAPIMockRecorder struct {
	mock *MockAppsAPI
}

// NewMockAppsAPI creates a new mock instance
func NewMockAppsAPI(ctrl *gomock.Controller) *MockAppsAPI {
	mock := &MockAppsAPI{ctrl: ctrl}
	mock.recorder = &MockAppsAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAppsAPI) EXPECT() *MockAppsAPIMockRecorder {
	return m.recorder
}

// CreateApp mocks base method
func (m *MockAppsAPI) CreateApp(ctx context.Context, language string, application openapi.Application) (openapi.InlineResponse2002, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApp", ctx, language, application)
	ret0, _ := ret[0].(openapi.InlineResponse2002)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateApp indicates an expected call of CreateApp
func (mr *MockAppsAPIMockRecorder) CreateApp(ctx, language, application interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApp", reflect.TypeOf((*MockAppsAPI)(nil).CreateApp), ctx, language, application)
}

// DeleteAppByUser mocks base method
func (m *MockAppsAPI) DeleteAppByUser(ctx context.Context, app string) (openapi.InlineResponse2002, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAppByUser", ctx, app)
	ret0, _ := ret[0].(openapi.InlineResponse2002)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteAppByUser indicates an expected call of DeleteAppByUser
func (mr *MockAppsAPIMockRecorder) DeleteAppByUser(ctx, app interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAppByUser", reflect.TypeOf((*MockAppsAPI)(nil).DeleteAppByUser), ctx, app)
}

// FetchAppByUser mocks base method
func (m *MockAppsAPI) FetchAppByUser(ctx context.Context, app string) (openapi.InlineResponse2003, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAppByUser", ctx, app)
	ret0, _ := ret[0].(openapi.InlineResponse2003)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FetchAppByUser indicates an expected call of FetchAppByUser
func (mr *MockAppsAPIMockRecorder) FetchAppByUser(ctx, app interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAppByUser", reflect.TypeOf((*MockAppsAPI)(nil).FetchAppByUser), ctx, app)
}

// FetchAppsByUser mocks base method
func (m *MockAppsAPI) FetchAppsByUser(ctx context.Context) (openapi.InlineResponse2003, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAppsByUser", ctx)
	ret0, _ := ret[0].(openapi.InlineResponse2003)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FetchAppsByUser indicates an expected call of FetchAppsByUser
func (mr *MockAppsAPIMockRecorder) FetchAppsByUser(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAppsByUser", reflect.TypeOf((*MockAppsAPI)(nil).FetchAppsByUser), ctx)
}
