// Code generated by MockGen. DO NOT EDIT.
// Source: api_instances.go

// Package testmocks is a generated GoMock package.
package testmocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	openapi "github.com/sdslabs/gctl/client"
	http "net/http"
	reflect "reflect"
)

// MockInstancesAPI is a mock of InstancesAPI interface
type MockInstancesAPI struct {
	ctrl     *gomock.Controller
	recorder *MockInstancesAPIMockRecorder
}

// MockInstancesAPIMockRecorder is the mock recorder for MockInstancesAPI
type MockInstancesAPIMockRecorder struct {
	mock *MockInstancesAPI
}

// NewMockInstancesAPI creates a new mock instance
func NewMockInstancesAPI(ctrl *gomock.Controller) *MockInstancesAPI {
	mock := &MockInstancesAPI{ctrl: ctrl}
	mock.recorder = &MockInstancesAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInstancesAPI) EXPECT() *MockInstancesAPIMockRecorder {
	return m.recorder
}

// FetchIntancesByUser mocks base method
func (m *MockInstancesAPI) FetchIntancesByUser(ctx context.Context) (openapi.InlineResponse2001, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchIntancesByUser", ctx)
	ret0, _ := ret[0].(openapi.InlineResponse2001)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FetchIntancesByUser indicates an expected call of FetchIntancesByUser
func (mr *MockInstancesAPIMockRecorder) FetchIntancesByUser(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchIntancesByUser", reflect.TypeOf((*MockInstancesAPI)(nil).FetchIntancesByUser), ctx)
}
