// Code generated by MockGen. DO NOT EDIT.
// Source: dbmaker.go

// Package testmocks is a generated GoMock package.
package testmocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	openapi "github.com/sdslabs/gctl/client"
	http "net/http"
	reflect "reflect"
)

// MockDbsAPIService is a mock of DbsAPIService interface
type MockDbsAPIService struct {
	ctrl     *gomock.Controller
	recorder *MockDbsAPIServiceMockRecorder
}

// MockDbsAPIServiceMockRecorder is the mock recorder for MockDbsAPIService
type MockDbsAPIServiceMockRecorder struct {
	mock *MockDbsAPIService
}

// NewMockDbsAPIService creates a new mock instance
func NewMockDbsAPIService(ctrl *gomock.Controller) *MockDbsAPIService {
	mock := &MockDbsAPIService{ctrl: ctrl}
	mock.recorder = &MockDbsAPIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDbsAPIService) EXPECT() *MockDbsAPIServiceMockRecorder {
	return m.recorder
}

// CreateDb mocks base method
func (m *MockDbsAPIService) CreateDb(ctx context.Context, databaseType string, localVarOptionals *openapi.CreateDBOpts) (openapi.InlineResponse2002, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDb", ctx, databaseType, localVarOptionals)
	ret0, _ := ret[0].(openapi.InlineResponse2002)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateDb indicates an expected call of CreateDB
func (mr *MockDbsAPIServiceMockRecorder) CreateDb(ctx, databaseType, localVarOptionals interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDb", reflect.TypeOf((*MockDbsAPIService)(nil).CreateDb), ctx, databaseType, localVarOptionals)
}

// DeleteDbByUser mocks base method
func (m *MockDbsAPIService) DeleteDbByUser(ctx context.Context, db string) (openapi.InlineResponse2002, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDbByUser", ctx, db)
	ret0, _ := ret[0].(openapi.InlineResponse2002)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteDbByUser indicates an expected call of DeleteDbByUser
func (mr *MockDbsAPIServiceMockRecorder) DeleteDbByUser(ctx, db interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDbByUser", reflect.TypeOf((*MockDbsAPIService)(nil).DeleteDbByUser), ctx, db)
}

// FetchDbByUser mocks base method
func (m *MockDbsAPIService) FetchDbByUser(ctx context.Context, db string) (openapi.InlineResponse2007, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDbByUser", ctx, db)
	ret0, _ := ret[0].(openapi.InlineResponse2007)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FetchDbByUser indicates an expected call of FetchDbByUser
func (mr *MockDbsAPIServiceMockRecorder) FetchDbByUser(ctx, db interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDbByUser", reflect.TypeOf((*MockDbsAPIService)(nil).FetchDbByUser), ctx, db)
}

// FetchDbsByUser mocks base method
func (m *MockDbsAPIService) FetchDbsByUser(ctx context.Context) (openapi.InlineResponse2007, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDbsByUser", ctx)
	ret0, _ := ret[0].(openapi.InlineResponse2007)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FetchDbsByUser indicates an expected call of FetchDbsByUser
func (mr *MockDbsAPIServiceMockRecorder) FetchDbsByUser(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDbsByUser", reflect.TypeOf((*MockDbsAPIService)(nil).FetchDbsByUser), ctx)
}
